### ISSUE TITLE
Can you please share the testing metric? Like the test error of 3.61 is in what units and what is the metric?

### ISSUE THREAD

**Issue by ankitranjan5** [IS2AI/thermal-facial-landmarks-detection#3]

**Comment by akuzdeuov** [comment]
Hello, 

We used Normalized Mean Error (NME) as a metric. There is no unit, only a range. 
![image](https://github.com/IS2AI/thermal-facial-landmarks-detection/assets/39990260/1fbd45e3-edf3-40b1-986f-b7491bc89ef4)
![image](https://github.com/IS2AI/thermal-facial-landmarks-detection/assets/39990260/080731d7-2056-4928-8062-cc26e9eabd6f)

**Comment by ankitranjan5** [comment]
Got it, thanks!
