### ISSUE TITLE
Help needed regarding error

### ISSUE THREAD

**Issue by aparnapandey08** [IS2AI/thermal-facial-landmarks-detection#4]
thermal-facial-landmarks-detection> python train_dlib_predictor.py --training dataset/gray/train/dlib_landmarks_train.xml --validation dataset/gray/val/dlib_landmarks_val.xml
[INFO] setting shape predictor options...
[INFO] shape predictor options:
shape_predictor_training_options(be_verbose=1, cascade_depth=20, tree_depth=4, num_trees_per_cascade_level=500, nu=0.01, oversampling_amount=20, oversampling_translation_jitter=0.1, feature_pool_size=750, lambda_param=0.1, num_test_splits=100, feature_pool_region_padding=0, random_seed=, num_threads=4, landmark_relative_padding_mode=1)
[INFO] training shape predictor...
Traceback (most recent call last):
  File "train_dlib_predictor.py", line 79, in <module>
    dlib.train_shape_predictor(args["training"],
RuntimeError: Error, the training dataset does not have any labeled object detections in it.
Can you please suggest ways to fix this

**Comment by akuzdeuov** [comment]
Hello, 

The problem might be in the path to the dataset. Could you try to provide the absolute path?

**Comment by aparnapandey08** [comment]
Thank you for your response , actually when it was giving an error
regarding root tag i removed<images> tag after dataset tat is why it was
giving error while training now i have again added the<images> tag and it
is fine.

**Comment by aparnapandey08** [comment]
---------------------------------------------------------------------------
*ValueError
Traceback (most recent call last) Cell In[37], line 1 ----> 1
generate_masks('dataset/gray/train/json') 2
generate_masks('dataset/gray/val/json') 3
generate_masks('dataset/gray/test/json'**) * *Cell **In[36], line 35 32
datasetPath="C:\\Users\\epe19\\thermal-facial-landmarks-detection\\dataset"
33 df = pd.read_csv(os.path.join(datasetPath, "challenging_images.csv"))
---> 35 if ((df['sub_id'] == int(sub_id)) & (df['trial_id'] ==
int(trial_id)) & (df['pos_id'] == int(pos_id))).any(): 36 print('Excluding:
', info) 37 continue ValueError**: invalid literal for int() with base 10:
'json\\100'*
Can you please help me in this error.
