### ISSUE TITLE
unet_mask_generation error

### ISSUE THREAD

**Issue by aparnapandey08** [IS2AI/thermal-facial-landmarks-detection#5]
NameError                                 Traceback (most recent call last)
Cell In[6], line 1
----> 1 generate_masks('dataset/gray/train/json')
      2 generate_masks('dataset/gray/val/json')
      3 generate_masks('dataset/gray/test/json')

Cell In[5], line 32, in generate_masks(jsonFolder)
     29 info = "{}_{}_{}".format(sub_id, trial_id, pos_id)
     31 # if image is challenging, skip it
---> 32 df = pd.read_csv(os.path.join(datasetPath, "challenging_images.csv"))
     34 if ((df['sub_id'] == int(sub_id)) & (df['trial_id'] == int(trial_id)) & (df['pos_id'] == int(pos_id))).any():
     35     print('Excluding: ', info)

NameError: name 'datasetPath' is not defined
can you please tell how to solve this , if i am replacing this with absolute path then there is other error

**Comment by akuzdeuov** [comment]
Hello, 

Thanks for reporting this issue. I updated the notebook by adding a path to the csv file: 
![image](https://github.com/IS2AI/thermal-facial-landmarks-detection/assets/39990260/77030e4c-0a08-4feb-b62d-0e1cd5090a57)
If you get the same error again then please try to update the path with an actual path to the file in your PC/laptop.
